# -*- coding: utf-8 -*-
"""
Created on Thu May 17 12:33:53 2012
@author: Nande!
simple hack, needs improving
execute like
python slideass.py directory_of_images
it uses .png files
"""

import sys,codecs
header= """[Script Info]
; Script generated by KickASS FX!
; http://kafx.com.ar/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes
Video Aspect Ratio: 0
Video Zoom: 6
Video Position: 0
Last Style Storage: Default
Collisions: Normal

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Trad,Footlight MT Light,34,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1,0,2,10,10,40,1
Style: Default,Eco-Files,20,&H00E3A85E,&H00FFFFFF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,1,2,8,10,10,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
dialogue = """Dialogue: 0,%s,%s,Default,,0000,0000,0000,,%s\n"""
enddiag = """Dialogue: 0,%s,%s,Default,,0000,0000,0000,1,Made Automagically with
Dialogue: 0,%s,%s,Default,,0000,0000,0030,1,KickASS FX! ( kafx.com.ar )
"""
def MSToTime(ms):
	"""Converts miliseconds in integer to a string from type '0:00:00.00' for ASS """
	string = "%s:%s:%s.%s"
	div, d = divmod(ms, 1000)
	d = int(d/10)
	div, s = divmod(div, 60)
	h, m = divmod(div, 60)
	return string %(h,m,s,d)

if __name__=='__main__':
	from libs import video
	import os
	import sys
	from os import path
	out = codecs.open("out.ass", "w", "utf-8")
	out.write(header)
	begin = 1500
	last = begin
	dur = 3000
	space = 500
	directory = sys.argv[1]
	for entry in os.listdir(directory):
		if  os.path.splitext(entry)[-1].lower()=='.png':
			ini = MSToTime(last)
			last += dur
			end = MSToTime(last)
			last += space
			fullpath = os.path.join(directory, entry)
			line = dialogue % (ini, end, fullpath)
			out.write(line)
	b=MSToTime(begin)
	line =enddiag %(b,end,b,end)
	out.write(line)
	out.close()